# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ployst Blog
email: 
description: The latest news from the ployst team
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.ployst.com" # the base hostname & protocol for your site
twitter_username:
github_username:  ployst

# Build settings
markdown: kramdown
